@baseurl = http://0.0.0.0:8000/
@advertisement_id = 1b707cff-dcf0-4f02-b73c-965233d9ecc6


### Создать объявление
POST {{baseurl}}/advertisement
Content-Type: application/json

{
  "title": "Продам ноутбук",
  "description": "Рабочий ноутбук, 8 ГБ ОЗУ, SSD",
  "price": 25000,
  "author": "Иванов И.И."
}
###

### Создать объявление
POST {{baseurl}}/advertisement
Content-Type: application/json

{
  "title": "Продам телефон",
  "description": "Рабочий телефон, 8 ГБ ОЗУ",
  "price": 5000,
  "author": "Белов А.А."
}
###

### Получить объявление по ID
GET {{baseurl}}/advertisement/{{advertisement_id}}
###

### Обновить объявление
PATCH {{baseurl}}/advertisement/{{advertisement_id}}
Content-Type: application/json

{
  "price": 6000
}
###

### Удалить объявление
DELETE {{baseurl}}/advertisement/{{advertisement_id}}
###

### Поиск объявлений (все)
GET {{baseurl}}/advertisement
###

### Поиск по заголовку и цене
GET {{baseurl}}/advertisement?title=ноутбук&min_price=24000&max_price=30000
###

### Поиск по заголовку и цене
GET {{baseurl}}/advertisement?title=телефон&min_price=2000&max_price=8000
###

### Поиск по автору
GET {{baseurl}}/advertisement?author=Иванов
###

### Поиск по автору
GET {{baseurl}}/advertisement?author=Белов
###